# Generated by Django 4.2.30 on 2026-06-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrsvp',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studysession',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
