# Generated by Django 4.2.27 on 2026-06-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sessionresource_sessionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='icon',
            field=models.CharField(default='users', max_length=50),
        ),
    ]
